package com.ai.ai_backend.service;

import com.ai.ai_backend.model.CandidateProfile;
import com.ai.ai_backend.memory.PersistentChatMemory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.client.advisor.MessageChatMemoryAdvisor;
import org.springframework.ai.chat.client.advisor.QuestionAnswerAdvisor;
import org.springframework.ai.converter.BeanOutputConverter;
import org.springframework.ai.vectorstore.SearchRequest;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.stereotype.Service;

@Service
public class AiService {

    private final ChatClient chatClient;
    private final VectorStore vectorStore; // 🔴 We need to save this to use it in the upload method!

    public AiService(ChatClient.Builder chatClientBuilder, PersistentChatMemory chatMemory, VectorStore vectorStore) {
        this.vectorStore = vectorStore; // Save it here

        this.chatClient = chatClientBuilder
                .defaultAdvisors(
                        new MessageChatMemoryAdvisor(chatMemory),
                        new QuestionAnswerAdvisor(vectorStore, SearchRequest.defaults())
                )
                .defaultFunctions("scheduleInterview")
                .build();
    }

    // 🔴 Standard Chat: Returns a conversational String
    public String askQuestion(String chatId, String question) {
        return chatClient.prompt()
                .user(question)
                .advisors(a -> a.param(MessageChatMemoryAdvisor.CHAT_MEMORY_CONVERSATION_ID_KEY, chatId))
                .call()
                .content();
    }

    // 🔴 NEW Extraction: Returns a strict Java Object
    public CandidateProfile extractCandidateProfile(String chatId) {
        // 1. Tell Spring AI what Java class we want to map to
        var outputConverter = new BeanOutputConverter<>(CandidateProfile.class);

        // 2. Get the strict JSON formatting rules generated by the converter
        String formatInstructions = outputConverter.getFormat();

        // 3. Ask the AI the question, and inject the formatting rules
        String rawJsonResponse = chatClient.prompt()
                .user(u -> u.text("Extract the candidate's professional profile from the provided resume document. \n{format}")
                        .param("format", formatInstructions))
                .advisors(a -> a.param(MessageChatMemoryAdvisor.CHAT_MEMORY_CONVERSATION_ID_KEY, chatId))
                .call()
                .content();

        // 4. Convert the raw JSON string into our actual CandidateProfile Java Object
        return outputConverter.convert(rawJsonResponse);
    }

    // 🔴 Dynamic PDF Upload & Vectorization
    public String processUploadedResume(org.springframework.web.multipart.MultipartFile file) {
        try {
            System.out.println("⚡ Receiving new resume: " + file.getOriginalFilename());

            // 1. Temporarily save the uploaded file so PDFBox can read it
            java.nio.file.Path tempFile = java.nio.file.Files.createTempFile("uploaded-resume", ".pdf");
            file.transferTo(tempFile);
            org.springframework.core.io.Resource pdfResource = new org.springframework.core.io.FileSystemResource(tempFile.toFile());

            // 2. Read the PDF
            System.out.println("1. Extracting text from uploaded PDF...");
            org.springframework.ai.reader.pdf.PagePdfDocumentReader pdfReader = new org.springframework.ai.reader.pdf.PagePdfDocumentReader(pdfResource);
            java.util.List<org.springframework.ai.document.Document> documents = pdfReader.get();

            // 3. Chunk the text
            System.out.println("2. Slicing text into chunks...");
            org.springframework.ai.transformer.splitter.TokenTextSplitter textSplitter = new org.springframework.ai.transformer.splitter.TokenTextSplitter();
            java.util.List<org.springframework.ai.document.Document> splitDocuments = textSplitter.apply(documents);

            // 4. Inject into the live Vector Database
            System.out.println("3. Injecting into live Vector Database...");

            // 🔴 THE CRITICAL MISSING LINE: Actually saving it to the AI's memory!
            this.vectorStore.add(splitDocuments);

            return "SUCCESS: I have successfully read and memorized the contents of " + file.getOriginalFilename();

        } catch (Exception e) {
            return "ERROR: Failed to process PDF - " + e.getMessage();
        }
    }
}